{"error":{"message":"Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla","stack":"Error: Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla\n    at NativeConnection.SafeMongooseConnection.onError (D:\\xeroBitTechnology\\xeroBitTechnology-BE\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at D:\\xeroBitTechnology\\xeroBitTechnology-BE\\node_modules\\mongoose\\lib\\connection.js:856:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla","service":"api","timestamp":"2023-03-15T06:27:21.788Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla","stack":"Error: Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla\n    at NativeConnection.SafeMongooseConnection.onError (D:\\xeroBitTechnology\\xeroBitTechnology-BE\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at D:\\xeroBitTechnology\\xeroBitTechnology-BE\\node_modules\\mongoose\\lib\\connection.js:856:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla","service":"api","timestamp":"2023-03-15T06:27:53.807Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla","stack":"Error: Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla\n    at NativeConnection.SafeMongooseConnection.onError (D:\\xeroBitTechnology\\xeroBitTechnology-BE\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at D:\\xeroBitTechnology\\xeroBitTechnology-BE\\node_modules\\mongoose\\lib\\connection.js:856:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://mongodb:27017/goodzilla","service":"api","timestamp":"2023-03-15T06:29:04.275Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (D:\\xeroBitTechnology\\xeroBitTechnology-BE\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at D:\\xeroBitTechnology\\xeroBitTechnology-BE\\node_modules\\mongoose\\lib\\connection.js:856:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","service":"api","timestamp":"2023-03-15T06:30:13.958Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (D:\\xeroBitTechnology\\xeroBitTechnology-BE\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at D:\\xeroBitTechnology\\xeroBitTechnology-BE\\node_modules\\mongoose\\lib\\connection.js:856:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","service":"api","timestamp":"2023-03-15T06:30:45.975Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (D:\\xeroBitTechnology\\xeroBitTechnology-BE\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at D:\\xeroBitTechnology\\xeroBitTechnology-BE\\node_modules\\mongoose\\lib\\connection.js:856:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","service":"api","timestamp":"2023-03-15T06:32:01.531Z"}
{"error":{"message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","stack":"Error: Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech\n    at NativeConnection.SafeMongooseConnection.onError (D:\\xeroBitTechnology\\xeroBitTechnology-BE\\src\\lib\\safe-mongoose-connection.ts:113:21)\n    at NativeConnection.emit (node:events:513:28)\n    at NativeConnection.emit (node:domain:489:12)\n    at D:\\xeroBitTechnology\\xeroBitTechnology-BE\\node_modules\\mongoose\\lib\\connection.js:856:30\n    at processTicksAndRejections (node:internal/process/task_queues:77:11)"},"level":"error","message":"Could not connect to MongoDB at mongodb://mongodb:27017/xerobittech","service":"api","timestamp":"2023-03-15T06:32:33.545Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Edit Failure , TypeError: updateBlog.save is not a function","service":"api","timestamp":"2023-03-15T10:25:50.400Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Edit Failure , CastError: Cast to ObjectId failed for value \"{}\" (type Object) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T10:28:31.057Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Edit Failure , CastError: Cast to ObjectId failed for value \"{}\" (type Object) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T10:38:12.375Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Add Failure , ValidationError: uuidBlog: Path `uuidBlog` is required.","service":"api","timestamp":"2023-03-15T11:22:45.077Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Add Failure , CastError: Cast to ObjectId failed for value \"http://localhost:3500/blog/edit\" (type string) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T11:48:17.743Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Add Failure , CastError: Cast to ObjectId failed for value \"http://localhost:3500/blog/edit\" (type string) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T11:48:29.024Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Add Failure , CastError: Cast to ObjectId failed for value \"http://localhost:3500/blog/edit\" (type string) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T11:48:39.158Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Add Failure , CastError: Cast to ObjectId failed for value \"http://localhost:3500/blog/edit\" (type string) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T11:50:56.409Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Add Failure , CastError: Cast to ObjectId failed for value \"http://localhost:3500/blog/edit\" (type string) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T11:51:11.473Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Add Failure , CastError: Cast to ObjectId failed for value \"http://localhost:3500/blog/edit\" (type string) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T11:51:28.494Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Cant Find , CastError: Cast to ObjectId failed for value \"6411ad1f19630b4298f85fb\" (type string) at path \"_id\" for model \"blog\"","service":"api","timestamp":"2023-03-15T11:55:00.742Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Cant Find , Error: Aggregate has empty pipeline","service":"api","timestamp":"2023-03-15T11:56:30.642Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Edit Failure , Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client","service":"api","timestamp":"2023-03-16T05:37:23.122Z"}
{"consoleLoggerOptions":{"label":"API"},"level":"error","message":"Edit Failure , Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client","service":"api","timestamp":"2023-03-16T05:37:49.460Z"}
